# Respect overrides from environment
BIOCONDA_UTILS_TAG=${BIOCONDA_UTILS_TAG:="v2.11.0"}
MAMBAFORGE_VER=${MAMBAFORGE_VER:="23.1.0-1"}
MAMBAFORGE_INSTALLATION_DIR=${MAMBAFORGE_INSTALLATION_DIR:="/opt/mambaforge"}
